language: haskell
cabal: "3.4" # Temporary pin until a sufficiently recent version is in the standard Travis images
addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc'
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

ghc:
  - '8.10'
  - '8.8'
  - '8.6'

script:
  - bash travis-build.sh

install: skip
